codestates-seb/seb44_main_004

server/build.gradle
server/src/main/java/com/seb_main_004/whosbook/curation/category/Category.java
server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
server/src/main/java/com/seb_main_004/whosbook/dto/PageInfo.java
server/src/main/java/com/seb_main_004/whosbook/exception/BusinessLogicException.java
server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
server/src/main/java/com/seb_main_004/whosbook/member/Member.java
server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
server/src/main/java/com/seb_main_004/whosbook/response/ErrorResponse.java
server/src/main/java/com/seb_main_004/whosbook/stubdata/Stub.java
server/src/main/java/com/seb_main_004/whosbook/vaildator/NotSpace.java
server/src/main/java/com/seb_main_004/whosbook/vaildator/NotSpaceValidator.java
server/src/main/resources/application.properties

도메인별로 엔티티클래스 작성 및 build gradle 의존 추가 및 공통 exception,vaildator 추가

Init/be entity 엔티티 클래스 초기셋팅

---

server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java

- BusinessLogicExcepton의 exceptionCode 추가
- exceptionCode 추가
- 도메인별 작업간 필요하다 생각되면 exceptionCode를 추가할 수 있다.
- 추가 시 기존의 exceptionCode양식을 준수한다.
- 추가로 필요한 부분이 있을 지 조언 부탁드립니다.

[BE] exceptionCode 추가

---

server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPostDto.java
server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java

-Member도메인 Post기능 구현
- API계층 부터 DB계층까지 Member 도메인 Post 기능 구현
- postDto에서 변수에 따른 유효성 검증
- JWT기능 구현을 위해 빠른 공유를 하기 위해서 다소 러프하게 작성하였습니다. 
- 이후 멤버 CRUD 보완할 예정입니다.

[BE] Member도메인 Post기능 구현

---

server/build.gradle
server/src/main/java/com/seb_main_004/whosbook/auth/dto/LoginDto.java
server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAccessDeniedHandler.java
server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationEntryPoint.java
server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationFailureHandler.java
server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationSuccessHandler.java
server/src/main/java/com/seb_main_004/whosbook/auth/jwt/JwtTokenizer.java
server/src/main/java/com/seb_main_004/whosbook/auth/userdetails/MemberDetailsService.java
server/src/main/java/com/seb_main_004/whosbook/auth/utils/CustomAuthorityUtils.java
server/src/main/java/com/seb_main_004/whosbook/auth/utils/ErrorResponder.java
server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
server/src/main/java/com/seb_main_004/whosbook/stubdata/Stub.java
server/src/main/resources/application.properties

jwt 로그인 인증, 해당 토큰 자격검증 구현 완료
<참고사항>
SecurityConfig 필터체인에있는 권한 설정 부분은 우선은 퍼밋올로 지정해뒀습니다
큐레이션과 해당요청에대한 팀원들과의 논의후 권한 설정 브랜치파서 해당 권한 설정후에 PR올리겠습니다

feat: jwt로그인 및 자격검증 구현 완료

---

server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java

CustomFilterConfigurer 메서드안에 jwtVerificationFilter 추가
delegateAccessToken메서드 안에 claim으로 memberId추가 => 이부분은 추후에 리팩토링을 예상하고있으므로 추가했습니다!

feat: CustomFilterConfigurer 메서드에 jwtVerificationFilter 추가

---

server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyPatchDto.java
server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyPostDto.java
server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/reply/mapper/ReplyMapper.java
server/src/main/java/com/seb_main_004/whosbook/reply/repository/ReplyRepository.java
server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java

댓글 작성 구현완료
로그인 검증쪽은 추후에 구현하고 PR날릴예정입니다
확인해주시고 궁금하신점은 리뷰 남겨주세요

feat:댓글작성 구현완료, 로그인검증 구현 예정

---

client/src/pages/CurationEditPage.tsx
client/src/pages/CurationWritePage.tsx

- 큐레이션 작성 페이지의 레이아웃을 작업 했습니다.
- 조금 전 Approve 해주신 큐레이션 '수정' 페이지와 동일한 레이아웃이기에 별도의 작업은 하지 않았습니다.
- 큐레이션 수정 페이지와 최상단 타이틀만 상이합니다 (큐레이션 '작성'하기)

큐레이션 작성 페이지 레이아웃 작업 완료

---

server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
server/src/main/java/com/seb_main_004/whosbook/reply/mapper/ReplyMapper.java
server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java

개요
-댓글 도메인 리팩토링-> 작성,수정,삭제 
작업사항
-댓글 작성시 curationId가져오는 부분추가
-댓글 수정,삭제시 로그인한 사용자와 댓글작성한 사용자가 일치하는지 검증하는 로직추가
-Member도메인과 연관관계 맵핑 추가
참고사항
-작업사항이많아 하나하나뜯어보고 모두 테스트해서 에러없는거까지확인했지만 제가빠뜨린부분이 있다면 리뷰 부탁드립니다
리뷰요청사항
-참고사항 부분과 동일합니다

[Server] 댓글 도메인 리팩토링

---

client/src/Routes.tsx
client/src/components/input/Input.tsx

- Router enum으로 관리
- Route path 처리 시 기존 문자열로 관리했던 코드를 RoutePath enum을 별도로 작성하였습니다.
- 앞으로 라우터 추가, 변경이 일어날 때는 RoutePath부분만 수정하시면 됩니다.
```tsx
export enum RoutePath {
Root = '/',
SignUp = '/register',
SignIn = '/login',
MyPage = '/mypage',
UserPage = '/userpage',
Write = '/write',
Edit = '/edit',
Detail = '/detail',
.. router..
}
<BrowserRouter>
<Routes>
<Route path={RoutePath.Root} element={<MainPage />} />
<Route path={RoutePath.SignUp} element={<SignUp />} />
<Route path={RoutePath.SignIn} element={<SignIn />} />
<Route path={RoutePath.MyPage} element={<MyPage />} />
<Route path={RoutePath.UserPage} element={<UserPage />} />
<Route path={RoutePath.Write} element={<CurationWritePage />} />
<Route path={RoutePath.Edit} element={<CurationEditPage />} />
<Route path={RoutePath.Detail} …
```

Router enum으로 관리

---

server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyPatchDto.java
server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java

개요
-댓글 수정시 insert문 쿼리 날라가는 이슈 해결 
=> update로 수정후 정상적으로 수정되는거까지 테스트 완료
작업사항
-ReplyController에서 댓글작성시 curationId불러오는 부분을 service에서 불러와서 저장하는것으로 수정
리뷰사항
-이슈 해결후 테스트완료했습니다! 리뷰부탁드립니다

댓글 이슈사항 리팩토링

---

server/src/main/java/com/seb_main_004/whosbook/advice/GlobalExceptionAdvice.java

- 공통 에러 핸들 기능
- `GlobalExceptionHandler` 추가
- 유효성 검사 메세지를 한번씩 점검하면 좋을 것 같습니다. 친절한 에러메세지!
-

feat: 공통 에러 핸들러 추가

---

server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java

- FE CORS 에러를 해결을 위해서 문제 해결
- setAllowedMethod 에 OPTIONS 를 추가

fix: setAllowedMethod 에 OPTIONS 추가

---

server/build.gradle
server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/com/seb_main_004/whosbook/auth/controller/HelloHomeController.java
server/src/main/java/com/seb_main_004/whosbook/auth/dto/LoginResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/seb_main_004/whosbook/auth/userdetails/MemberDetailsService.java
server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
server/src/main/resources/application.properties
server/src/main/resources/templates/hello-oauth2.html

-프론트쪽 요청사항
로그인 성공시 body에 memberId, nickname,imgurl정보 담기
cors에 Refresh추가
로그인 성공시 body에 memberId, nickname,imgurl정보 담기
cors에 Refresh추가
프론트쪽의 요청사항으로 인한 작업입니다

Refator/be jwtlogin 프론트 요청사항

---

server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java

-프론트 요청사항
-시큐리티 설정파일에 origin 프론트 배포주소 추가
-확인부탁드립니다

refactor:오리진 주소 추가

---

client/src/App.tsx
client/src/Routes.tsx
client/src/components/gnb/GlobalNavigationBar.tsx
client/src/pages/Curation/CurationEditPage.tsx
client/src/pages/MainPage.tsx
client/src/pages/User/SignIn.tsx
client/src/pages/User/SignUp.tsx
client/src/store/userSlice.ts

login 후 memberId, nickname 정보 저장

---

server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java

fix:json타입 추가

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java

소셜로그인 응답바디 데이터 추가했습니다
확인부탁드립니다

fix: 소셜로그인 응답바디 데이터 추가

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java

소셜로그인 변경사항입니다
데이터를 db에 저장하는 부분변경, host프론트주소로 변경했습니다
확인부탁드려요

fix:sucess핸들러 빠진부분 추가,host 변경

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java

소셜로그인 host,path변경사항이있어서 올립니다!
확인해주세요!

fix:oauth핸들러 수정

---

client/src/api/userApi.ts
client/src/components/header/DropdownMenu.tsx
client/src/components/header/GlobalNavigationBar.tsx
client/src/components/imageUpload/ImageUpload.tsx
client/src/components/modals/Modal.tsx
client/src/pages/User/SignIn.tsx
client/src/pages/User/SignUp.tsx
client/src/store/modalSlice.ts
client/src/utils/image.ts
client/src/utils/validation.ts

- 회원가입, 마이페이지에서 수정 시 프로필 이미지 업로드 기능 구현
- 이미지 미리보기 함수 `image.ts` 파일로 분리
- 이미지 File name 변경 함수 `image.ts` 파일로 분리
- 네비게이션에서 선택한 페이지가 로그인, 마이페이지, 큐레이션 작성일 때는 기존 선택했던 메뉴에 적용했던 스타일 제거 (폰트 컬러, 밑줄)
<br/>
`ImageUpload.tsx`
```tsx
interface IProps {
nickname?: string; // form에서 작성한 유저의 nickname
selectImg: string; // 미리보기 이미지 주소
handleSelectImage: (imgURL: string) => void; // 미리보기에 넣을 이미지 주소값을 정보를 업데이트하는 함수
handleFileInfo: (file: File) => void; // File 객체의 정보를 업데이트하는 함수
}
```
<br/>
- 추가 수정할 부분이 있을 지 조언 부탁드립니다.

회원가입, 마이페이지 수정에서 쓰이는 이미지 업로드 기능

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java

test용입니다
자주 PR을 날릴거같습니다
그래서 앞으로 조그만한 변동사항이면 제가머지하도록 하겠습니다
양해부탁드립니다

fix:데이터 저장 위치 변경(test용 PR입니다)

---

server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java

소셜로그인 테스트용 PR
시큐리티 컨피그레이션 오리진 주소 추가

fix:origin주소 추가

---

server/src/main/resources/application.yml

yml파일에 리다이렉트 URI추가
확인부탁드립니다 
yml파일 설정하고 오류는 없이잘실행되었습니다

fix:yml파일에 리다이렉트 URI추가

---

server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java

fix:status추가(test용)

---

server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java

fix:cors설정

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java

fix:테스트 삭제

---

server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java

- 좋아요한 큐레이션 목록 조회 API
- 내가 좋아요한 큐레이션 목록 조회 API 구현
- 타 회원이 좋아요한 큐레이션 목록 조회 API 구현
- JPA repository 쿼리문은 nativeQuery을 활용하여 작성
- 로컬테스트 완료
- 궁금한 점이나 개선할 점이 있다면 코멘트 남겨주세요.

feat: 좋아요한 큐레이션 목록 조회 API

---

server/src/main/java/com/seb_main_004/whosbook/curation/category/Category.java
server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryAllPostDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryController.java
server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryPostDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryRepository.java
server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryService.java
server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationListResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java

- 큐레이션 카테고리 기능 구현
- 큐레이션, 카테고리 엔티티 연관관계 맵핑
- 카테고리 CRD 구현 (Update 는 추후 구현 예정)
- List 형태로 초기 카테고리 한번에 등록 가능
- 큐레이션 작성시 카테고리 ID 지정 필수
- 큐레이션 수정시 카테고리 ID 지정 필수
- 큐레이션 수정시 카테고리 수정 가능
- 모든 카테고리 조회 API 매핑
- 큐레이션 조회시 응답데이터에 categoryId, category 필드 추가
- 일단 빠르게 필요한 부분만 만들기 위해서 카테고리 수정 부분은 제외 했습니다. 해당 부분은 추후 업데이트 하겠습니다 !
- 큐레이션 수정시 카테고리 변경 기능은 구현했습니다.
```json
{
"curator": {
"memberId": 1,
"email": "bbb@naver.com",
"nickname": "테스트5",
"introduction": null
},
"categoryId": 10,
"category": "스포츠",
"isLiked": false,
"isSubscribed": true,
"curationLikeCount": 0,
"curationId": 7,
"emoji": "✨👍🔥",
"title": "카테고리 테스트 합니다 큐레이션션",
"content": "카테고리 테스트 합니다 카테고리 테스트 합니다카테고리 테스트 합니다카테고리 테스트 합니다카테고리 테스트 합니다 ",
"imageIds": [],
"visibility": "PUBLIC",
"createdAt": "2023-07-17T17:20:50",
"updatedAt": …
```

feat: 카테고리 기능 구현

---

server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java

- 단일 상세 큐레이션 조회시 사용자에 따른 큐레이터 구독 여부 응답
- `CurationService` 에서 `getCuration()` 메소드에서 로그인한 유저일 경우 해당 멤버가 큐레이터를 구독하는지 확인하는 로직 추가
- 구독 중이면 Curation 엔티티 안에 isSubscribed 값을 true로 변경
- 단일 상세 조회 쿼리가 어마무시해서 리팩토링을 고민해봐야 할 거 같습니다
- 다른 부분에서 염려되는 부분이나 수정 할 부분 리뷰 부탁드립니다!

feat: isSubscirbed 기능 구현

---

server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryController.java
server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryPostDto.java

- 단일 카테고리 등록 안되는 문제 해결
- @Builder 어노테이션과 @Data 어노테이션 충돌 해
https://young-meeting-892.notion.site/f819031beb5d423986e8a91071193b7e?pvs=4
참고링크

Fix: 단일 카테고리 등록 안되는 문제 해결

---

server/src/main/java/com/seb_main_004/whosbook/auth/utils/CustomAuthorityUtils.java

fix:권한 생성 수정

---

server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java

feat: 시큐리티 컨피그 인가설정

---

server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java

fix: 마이페이지 소셜로그인 수정

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java

feat: 소셜로그인

---

server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java

fix:socaltest

---

server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java

fix:맴버컨트롤러 분기 수정

---

server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
server/src/main/java/com/seb_main_004/whosbook/member/dto/CuratorResponseDto.java

fix: 회원가입시 토큰

---

client/src/api/axios.ts
client/src/api/mainPageApi.ts
client/src/api/userApi.ts
client/src/components/alert/sweetAlert.ts
client/src/components/cards/CurationCard.tsx
client/src/components/cards/CuratorCard.tsx
client/src/components/cards/MainCurationCard.tsx
client/src/components/slider/CardSlider.tsx
client/src/components/slider/SimpleSlider.tsx
client/src/pages/Curation/CurationEditPage.tsx
client/src/pages/MainPage.tsx
client/src/pages/User/SignIn.tsx
client/src/store/userSlice.ts
client/src/styles/GlobalStyles.ts
client/src/types/card.ts
client/src/types/main.ts
client/src/types/user.ts

- sweet alert 추가
- 커스텀 에러 핸들링 하기 위해 `axios interceptor`로 error 핸들링 하던 코드 전체 삭제 
- `sweetalert2` 적용하였습니다.
- response 응답시 에러가 발생했을 때 `axios.interceptor.reponse` 내 코드에서 에러에 따라 해당 에러 페이지로 갈 수 있도록 구현했었는데 alert창을 띄우실 수 있도록 기존 코드를 없앴습니다.
- 빌드시 에러 해결(`SelectBox.tsx`에서 `setCategoryId`함수를 prop으로 받는데 `CurationEditPage.tsx`에서 `setCategoryId`함수를 전달해주지 않아 에러가 났습니다. 이부분 참고바랍니다.
<br/>
```ts
import Swal from 'sweetalert2';
interface AlertSettings {
// 속성들은 확장가능합니다. 필요하시다면 추가해주셔도 됩니다. 추가될 경우 optional로 해주세요.
title: string;
text: string;
icon: 'success' | 'error' | 'warning' | 'info' | 'question';
confirmButtonText: string;
confirmButtonColor: string;
}
export const customAlert = ({
title,
text,
icon,
confirmButtonText,
confirmButtonColor,
}: AlertSettings) => {
Swal.fire({
title,
text,
icon, …
```

공통으로 쓰일 sweet alert 적용

---

client/src/components/curations/CurationDetailInfo.tsx
client/src/pages/Curation/CurationDetailPage.tsx

단일 상세 페이지에서 나타난 오류 중 제 파트만 리팩토링 하였습니다.
- 댓글 부분에서 0 이 뜨는 오류를 수정하였습니다.
- 자신의 큐레이션 단일 상세 페이지일 경우에도 좋아요 꽉찬 하트가 표시 되게 하였습니다.
- 자신의 큐레이션이 아닐 때는 수정/삭제하기 버튼이 보이지 않게 수정하였습니다.
- 모든 큐레이션에서 같은 댓글들이 똑같이 발생하는 것을 수정하였습니다. 
- 세 번째의 유저에 따른 수정/삭제하기 버튼 유무 오류는 연수님의 코드를 약간 수정하였습니다.  
- isAuthor() 함수에서 비교하는 값을 로그인한 유저(나)의 memberId 와 curator.memberId 로 수정하였습니다.
- 댓글 0 
| 수정 전 | 수정 후|
|:--:|:--:|
|![image](https://github.com/codestates-seb/seb44_main_004/assets/76391160/2b2bcf56-238e-4160-9c07-87ca6a954650)|![image](https://github.com/codestates-seb/seb44_main_004/assets/76391160/cbc71d2d-0a04-4222-b860-c530e4ab32d9)|
- 좋아요 하트 표시 (자신이 쓴 큐레이션 페이지에서)
|수정 전| 수정 후|
|:--:|:--:|
|![image](https://github.com/codestates-seb/seb44_main_004/assets/76391160/49cef4be-be3a-4f8f-b29b-0d485371687e)|![image](https://github.com/c …

단일 상세 페이지에서 리팩토링

---

client/src/components/cards/MainCurationCard.tsx
client/src/components/curations/CurationDetailInfo.tsx
client/src/components/curations/CurationProfileInfo.tsx
client/src/components/profiles/ProfileInfo.tsx
client/src/pages/Curation/CurationDetailPage.tsx
client/src/pages/Curation/CurationEditPage.tsx
client/src/pages/User/SignIn.tsx
client/src/styles/GlobalStyles.ts
client/src/utils/image.ts

-  로그인전에 로그인이 필요한 기능을 사용하기 위해 로그인 한 뒤 이전에 보고있던 해당 페이지로 이동

#250 이전 페이지 정보 저장

---

server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationFailureHandler.java
server/src/main/java/com/seb_main_004/whosbook/auth/userdetails/MemberDetailsService.java
server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java

feat: 에러메세지 수정

---

server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationEntryPoint.java
server/src/main/java/com/seb_main_004/whosbook/auth/utils/ErrorResponder.java

fix:에러 처리 수정

---

client/src/Routes.tsx
client/src/api/profileApi.ts
client/src/api/userApi.ts
client/src/components/modals/Modal.tsx
client/src/components/profiles/ProfileForm.tsx
client/src/components/profiles/ProfileOut.tsx
client/src/pages/Curation/CurationDetailPage.tsx
client/src/pages/User/MyPage.tsx

단일 상세 페이지 - 댓글 이슈, alert 변경
- 댓글 비회원 작성시 alert 창 뜨게
- 기존 alert 를 지예님께서 만드신 컴포넌트로 대체

단일 상세 페이지 - 댓글 이슈, alert 변경

---

client/src/components/cards/CurationCard.tsx
client/src/components/cards/MainCurationCard.tsx

- 닉네임이 길어길 경우에 말줄임을 이용해 카드 컴포넌트를 수정하였습니다.

큐레이션 카드 닉네임 오류 리팩토링

---

client/src/components/cards/MainCurationCard.tsx
client/src/components/curations/CurationCreatedDate.tsx
client/src/components/curations/CurationDetailInfo.tsx
client/src/components/curations/CurationProfileInfo.tsx
client/src/pages/Curation/CurationDetailPage.tsx

- 카테고리 버튼 hover 시 클릭 안되게, 색 안변하게 변경
- 큐레이션 단일 상세 페이지 닉네임이 길 때 구독하기 버튼이 밀리는 현상 리팩토링
- 닉네임이 길 경우
- 닉네임이 짧을 경우
- 타유저가 쓴 단일 상세 큐레이션 페이지일 경우
- 댓글이 없을 경우, 멘트 변경

단일 상세 페이지 오류 리팩토링

---

client/src/components/profiles/ProfileCard.tsx
client/src/pages/Curation/BestCurationPage.tsx
client/src/pages/Curation/NewCurationPage.tsx

- 페이지네이션 버튼 클릭 이슈를 css 로 변경함에 따른 리팩토링을 진행하였습니다.
클릭시 네모 박스를 클릭시 페이지네이션이 구현되지 않는다는 이슈에 따라서
hover 시 글씨 색만 변하게 해서 글자에 클릭되도록 유도하였습니다.
active 활성화 할 때는 사진과 같이 구현하였습니다.

pagination css 변경

---

client/src/components/profiles/ProfileForm.tsx
client/src/components/profiles/ProfileInfo.tsx
client/src/pages/User/MyPage.tsx

- 회원 수정 시 발행 버튼을 누르면 반영이 되지 않는 부분에 대한 이슈가 있었습니다.
- 아무래도 e.preventDefault() 를 적용시키지 않은 부분이 원인이라고 생각하여, 코드를 추가하였습니다.
- 마이페이지 프로필 상단에서 유저의 이름을 가져오는 부분에서 useEffect 를 추가하였습니다.

마이페이지 회원 수정 에러 리팩토링

---

client/src/pages/Curation/BestCurationPage.tsx
client/src/pages/Curation/NewCurationPage.tsx

- BEST/NEW 카테고리 페이지에서 ```전체 카테고리 보기``` 버튼을 추가하여, api 연결하였습니다.
- css 부분은 수정 하셔도 됩니다.

전체 카테고리 버튼 리팩토링

---

client/src/api/profileApi.ts
client/src/api/userApi.ts
client/src/components/header/GlobalNavigationBar.tsx
client/src/components/imageUpload/ImageUpload.tsx
client/src/components/profiles/ProfileForm.tsx
client/src/pages/Curation/CurationDetailPage.tsx
client/src/pages/MainPage.tsx
client/src/pages/User/SignUp.tsx
client/src/styles/GlobalStyles.ts

- 프로필 이미지 삭제 후 기본 프로필 이미지로 가입 시 이전에 선택한 사진으로 가입되는 에러 해결
- 소셜 가입 시 사진 삭제 후 가입이 안 되는 에러 해결
- 회원탈퇴 후 토큰을 삭제하지 않아 계속 로그인 상태였던 것 -> 회원 탈퇴하면 서버 응답값이 204일 때 토큰 삭제하여 처리
- 회원탈퇴 후 서버에서 로그인 처리를 해서 보내주는 문제, 회원 정보를 가져오는 요청에서 토큰 이상 여부를 판별하기 때문에
프론트에서 임시적으로 에러 핸들링
- 비회원이 회원가입을 쉽게 접근할 수 있도록 메뉴에 회원가입 버튼 추가 (기존 로그인 페이지에서만 회원가입 페이지를 갈 수 있었던 불편함)

이미지 업로드 버그 수정

---

client/src/pages/MainPage.tsx

- 메인페이지에서 더보기를 클릭시 링크를 잘못 연결시킨 부분 수정했습니다.

메인페이지 더보기 이슈 리팩토링

---

client/src/api/profileApi.ts
client/src/components/replies/ReplyProfileInfo.tsx

- 탈퇴한 유저페이지 접속시 404에러 처리 코드 추가
- 댓글에서 닉네임 클릭시 유저페이지로 이동

유저페이지 접속시 탈퇴회원 에러 처리 및 댓글 닉네임 클릭시 유저페이지로 이동

---

server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationFailureHandler.java

fix:탈퇴시 로그인처리 status변경

---

.github/workflows/gradle.yml

- Unhandled Exception 에러로그 슬랙 연동을 위한 작업
- 깃헙 액션 CD 를 위한 환경변수 설정
- 해당 부분은 디스코드에 공유했었습니다 혹시 모르시면 다시 디스코드에 알려주세요

Config: 깃헙 액션 CD를 위한 환경변수 설정

---

client/src/pages/User/SignIn.tsx

- 일반 로그인 정보 입력 후 `구글로 로그인 하기` 버튼 클릭시 `일반 로그인 처리`가 된후 -> `구글 로그인 선택 창으로 가는 버그` 수정

fix: google login 버그 수정
