- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- server/src/main/java/com/seb_main_004/whosbook/utils/UriCreator.java
- server/src/main/resources/application.properties
- HTTP POST 메소드를 통해 `/curations` 호출시 질문 작성
- 회원과 연관관계 맵핑은 아직 안 되어있음
- 질문 작성을 위한 컨트롤러, 서비스, 맵퍼, 리파지토리, DTO 코드 작성
- 모든 유효성 추가
- application.properties에 로그 색상 변경 설정 추가
- 추후 Member 클래스와의 연관관계 맵핑 필요
- 추후 Category 클래스와의 연관관계 맵핑 필요
- 엔티티랑 DTO 관련해서 빠진 부분 없는지 한번 더 체크 부탁드립니다.
> Feat/be-curationPost 큐레이션 작성 기능 추가

- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 회원 기능을 제외한 큐레이션 수정 기능
- 큐레이션 수정 기능을 위한 DTO, Service, Controller, Entity 클래스에 메소드 추가
- 삭제 된 글을 수정 할 시 비지니스 에러 추가
- 수정 완료시 헤더 `Location` key에 단일 상세 조회 uri 응답
- 사용자가 기존 데이터를 토대로 수정하는 것이기에 변경된 필드만 찾기 어려워 모든 데이터를 수정하는 로직으로 구현
- 작성한 회원만 해당 큐레이션을 수정 할 수 있는 로직은 추후 추가 예정
- 인가 관련 부분 제외하고 다른 부분에서 문제 없는지 확인 부탁드립니다.
> Feat/be-curationModify 큐레이션 수정 기본 기능 구현 (회원 제외)

- client/src/components/CurationCard.tsx
- client/src/components/SubCuratorCard.tsx
- 큐레이션 카드, 마이페이지에서 쓰이는 큐레이터 카드 레이아웃 구현
</br>
- 큐레이션 카드, 큐레이터 카드 레이아웃, css 적용(hover 포함)
</br>
- 큐레이션 카드 ```CurationCard.tsx``` 
-  부모 컴포넌트로부터 ```emoji```, ```title```, ```content```, ```likes```, ```nickname``` 을 받아오는 것으로 설정
- 마이페이지에서는 가로로 두 개씩, 나머지 페이지에서는 가로로 세 개씩 렌더링 되는 부분이라 width 적용은 추후 할 계획 
- 큐레이터 카드 ```SubCuratior.tsx``` 
- 추후 props 설정 할 계획
- 프로필 이미지 부분은 이미지가 존재할 경우에는 이미지로 대체되며, 그렇지 않을 경우 기본 React-icons 로 보여집니다.
</br>
1.  큐레이션 카드
2. 큐레이터 카드
</br>
- 스크린샷 보시고 혹시나 수정할 부분이 있으면 조언 부탁드립니다.
> Feat/fe-curationCard 큐레이션 카드 컴포넌트 레이아웃 구현

- server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
- server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPostDto.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberResponseDto.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/MultiResponseDto.java
- server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
- server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
- server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
- server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
- 멤버 도메인 CRUD 구현
- 멤버 도메인 CRUD 구현
- memberPostDto에서 memberId 변수 제거
- member도메인 변수에 'introduction(자기소개)' 추가
-> 자기소개는 회원가입 후 마이페이지에서 최초작성 및 수정이 가능한 것으로 상정
- memberService에 회원 이메일 검증 메소드 추가
- get과 gets는 추후 연관관계 매핑 후 큰 폭으로 수정될 것으로 예상
** 현재 인증기능과의 연동은 없는 기본CRUD 입니다. 추후 연동할 예정입니다.  
> [BE] 멤버도메인 CRUD(인증기능 미포함)

- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 큐레이션 작성, 수정 시 회원과 관련된 기능 추가
- Member, Curation 엔티티 연관관계 맵핑
- 질문 작성시 `SecurityContextHorder` 에서 `Authentication`의 `principal` 호출하여 사용자 이메일 검색
- 검색된 사용자를 작성되는 큐레이션에 넣어 저장
- 질문 수정시 위와 같은 방법으로 로그인한 사용자 이메일과 작성자 이메일이 동일한지 검증 후 수정
- MemberService 클래스에 필요한 메소드가 있어서 동욱님께 요청드렸습니다. 그대로 머지 하게 되면 dev에서 pull 받아오면 에러가 발생 할 수 있으니 동욱님 PR이 먼저 머지되면 머지 하겠습니다.
- 보시고 궁금하시거나 보완이 필요한 부분 말씀해주세요.
> feat: 큐레이션 작성 수정시 회원관련 기능 추가

- client/src/components/quill/QuillEditor.tsx
- client/src/pages/CurationEditPage.tsx
- client/src/styles/GlobalStyles.ts
- 큐레이션 수정 페이지의 레이아웃을 작업 했습니다.
- 웹 에디터 React Quill을 적용했습니다.
- 책 카테고리를 선택할 수 있도록 select box를 적용했습니다.
- 추후 책 API를 활용해 정보를 등록할 수 있도록 검색 버튼을 적용했습니다.
- 큐레이션 공개 여부를 선택할 수 있도록 라디오 버튼을 적용했습니다.
- 그 외 title, input, button은 공통 컴포넌트를 사용했습니다.
- 카테고리 부분은 책 카테고리가 다양하므로 추후 별도의 컴포넌트로 뺄 예정입니다.
- 책 API 기능과 모달이 구현되면 추후 함께 적용 예정입니다.
- 제목과 이미지가 같은 input창에 입력되던 문제는 value를 다르게 하여 해결했습니다.
- 내용 input 창에 bold와 italic이 적용되지 않던 문제는 GlobalStyles.ts 하단에 strong과 em을 추가해 해결했습니다.
https://github.com/codestates-seb/seb44_main_004/assets/123397411/884600f7-2d4f-48b7-ba8d-64f29e7ca67d
- 도움 주셔서 감사합니다! 피드백은 언제나 환영입니다.
- 확인해 주시면 큐레이션 '작성' 페이지도 위 레이아웃 적용해 PR 올리겠습니다.
> 큐레이션 수정 페이지 레이아웃 작업 완료

- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
- 로그인한 사용자가 본인이 작성한 큐레이션을 삭제하는 기능
- 로그인한 사용자와 큐레이션 작성자가 일치하는 지 검증
- 이미 삭제된 큐레이션에 접근하는 경우 `BusinesLogicException` 발생
- Exception 코드 변경 `_CURATION_HAS_BEEN_DELETED_`
- 코드 403 -> 404
- 메세지 "큐레이션이 삭제되었습니다." -> "이미 삭제된 큐레이션입니다."
- 이유 : 이미 삭제된 큐레이션에 접근하는 요청에 대한 에러코드이기 때문에 위와 같이 변경되야 된다고 생각했습니다.
- 사용자 검증이 완료되었다면 `CurationStatus` active -> delete 로 변경
- 컨트롤러에 Authentication 을 얻기위해 `private` 메소드로 만든 부분을 리팩토링해서 검증된 email을 리턴해주는 거로 변경했습니다.
- 개선해야하거나 궁금하신점 리뷰로 남겨주세요!
> feat: 큐레이션 삭제 기능

- client/src/components/CurationCard.tsx
- client/src/components/SubCuratorCard.tsx
- 마이페이지 연결 작업을 하면서 호환성에 맞게 큐레이션 카드 컴포넌트를 수정했습니다.
- 큐레이션 카드 컴포넌트
- type 속성을 추가하여 페이지에 맞게 width 가 조절되도록 변경하였습니다.
- 폰트 사이즈를 변경하였습니다. 
- 구독 큐레이터 카드 컴포넌트
- props 로 닉네임, 구독자수, 작성한 큐레이터 수, 소개글 을 받아오도록 설정하였습니다.
- 디스코드의 의견을 반영하여 width 를 변경하였습니다. 
- 소개글 부분은 말줄임이 되도록 설정해 놓았습니다.
(아토미한 컴포넌트다 보니 연결 작업 시 수정 사항이 자주 발생할 것 같습니다.)
**추가! card 폴더생성해서 옮긴다는 것을 깜빡했습니다. 다음 수정 사항에 꼭 반영하도록 하겠습니다.** 
- 큐레이션 카드 컴포넌트
- type 속성을 optional 로 설정하였고, ```mypage``` 일 경우와 그렇지 않은 경우로 나누었습니다.   
- 큐레이션 카드 컴포넌트
|마이페이지인 경우| 메인페이지나 큐레이션 리스트 페이지인 경우|
|:--:|:--:|
|<img width="1283" alt="스크린샷 2023-07-06 오후 2 06 44" src="https://github.com/codestates-seb/seb44_main_004/assets/76391160/e97241e7-34e7-49b2-8ee5-1796b0c76f73" > | <img width="1146" alt="스크린샷 2023-07-06 오후 2 10 30" …
> Feat/fe-curationCard 큐레이션 카드 컴포넌트 레이아웃 수정

- server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
- server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyPatchDto.java
- server/src/main/java/com/seb_main_004/whosbook/reply/mapper/ReplyMapper.java
- server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java
개요
-큐레이션 단일상세조회에서 로그인한 사용자가 쓴 댓글을 수정,삭제할수있습니다
작업사항
-댓글 수정,삭제 구현
-로그인한 사용자가 댓글 수정,삭제할수있게인증 처리까지 구현
참고사항
-ReplyService에서 로그인한사용자와댓글을 작성한 사용자가 일치하는지 검증하는 로직 구현은 연관관계 맵핑후 구현할 예정
리뷰요청사항
-참고사항이외에 처리할부분이있는지 리뷰 부탁드립니다
> feat: 댓글수정,삭제 구현 완료

- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/CuratorResponseDto.java
- server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
- HTTP GET 메소드를 통한 큐레이션 단일 상세 조회 API
- 단일 상세 조회 응답을 위한 `CurationSingleDetailResponseDto` 구현
- `CurationMapper` 에 맵핑 메소드 추가
- `Reply` 엔티티와 `Curation` 엔티티 연관관계 맵핑
- `CuratorResponseDto` 생성
- 연관관계 맵핑이라 문제 될게 없는지 확인 부탁드립니다.
> feat: 큐레이션 단일 상세 조회 기능 구현

- client/src/components/buttons/Button.tsx
- 공통 버튼 컴포넌트에 detail 버튼 스타일을 추가했습니다.
- 공통 버튼 컴포넌트에 더보기 버튼 (type='detail') 으로 스타일을 적용하였습니다.
- 단순히 댓글을 더 불러오는 기능을 하는 버튼이기에, 클릭 및 hover 시 색이 변하는 스타일을 적용하진 않았습니다.
```tsx
<Button type="detail" content="더보기" />
```
https://github.com/codestates-seb/seb44_main_004/assets/123397411/488ace3d-f3a3-4c27-a7c1-e01561aa07f9
- 추가 수정할 부분이 있을 지 조언 부탁드립니다.
<br/>
> [Client] 공통 버튼 컴포넌트에 detail 스타일 추가

- client/src/components/buttons/Button.tsx
- client/src/styles/theme.ts
- 공통 버튼 컴포넌트에 category 버튼 스타일을 추가했습니다.
- 공통 버튼 컴포넌트에 카테고리 버튼 (type='category') 으로 스타일을 적용하였습니다.
- 더불어, theme.ts의 mainLightBlack200에 `#`을 추가했습니다.
- 공통 스타일에서 추가로 width, radius, shadow 스타일을 적용했습니다.
```tsx
<Button type="category" content="경영 / 경제" />
```
https://github.com/codestates-seb/seb44_main_004/assets/123397411/cd2bfe2a-f178-4431-ab7c-07c999a4870f
- 피드백은 언제나 환영입니다!
<br/>
> [Client] 공통 버튼 컴포넌트에 category 스타일 추가

- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 큐레이션 삭제 상태가 데이터베이스에 저장되지 않는 문제 해결
- `CurationService` 단에 수정된 `Curation` 엔티티를 리파지토리를 통해 데이터 베이스에 저장하는 로직 추가
- 스크럼 때 컨펌을 받아 바로 머지 하겠습니다
-
> fix: 큐레이션 삭제 상태가 데이터베이스에 저장이 되지 않는 문제 해결

- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
- server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
- server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
- server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
- 멤버 도메인 페이지네이션 기능 관련 리팩토링
- getMyCurations(내가 작성한 큐레이션 목록 조회) 페이지네이션 구현
- getMyMembers(내가 구독한 큐레이터 목록 조회) 페이지네이션 리팩토링
- getMyCurations 페이지네이션을 구현하며, 기존의 복잡했던 코딩을 보다 직관적으로 리팩토링했습니다.
- getMyMembers 페이지네이션 기능 '현재 페이지 조회'에서 오류가 발생하여, 해당 오류를 해결하는 리팩토링 진행했습니다.
- 로컬테스트 완료
- 참고사항의 이외에 추가로 예외 처리가 필요한 부분이나, 궁금한 점이 있다면 피드백 주시기 바랍니다.
> Feat: Member도메인 페이지네이션 리팩토링

- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
- server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
- server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
- server/src/main/java/com/seb_main_004/whosbook/subscribe/entity/Subscribe.java
- server/src/main/java/com/seb_main_004/whosbook/subscribe/service/SubscribeService.java
- 타 유저가 작성한 큐레이션 목록 조회 API구현
- Subscribe 리팩토링
- 타 유저가 작성한 큐레이션 목록 조회 API구현
- Subscribe 리팩토링
--> 기존의 Subscribe 도메인은 post, delete 동작 시 status를 변경하는 방식으로 동작하였음
--> 이를 테이블을 생성하고 삭제하는 방식으로 변경함 (데이터베이스 리소스 절약과, 매핑작업의 간결화 등의 이유)
- 로컬테스트 완료
- 개선해야 할 부분이나 궁금한 점이 있다면, 코멘트 남겨주십시오.
> feat: 타 유저가 작성한 큐레이션 목록 조회 API

- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationImageDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationSaveImageRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationImageService.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
- server/src/main/java/com/seb_main_004/whosbook/image/service/S3StorageService.java
- server/src/main/java/com/seb_main_004/whosbook/image/service/StorageService.java
- server/src/main/java/com/seb_main_004/whosbook/image/utils/ImageStorageUtils.java
- 큐레이션 작성시 웹에디터를 통해 이미지 수정 기능을 위한 구현
- Dto 유효성 검사 수정 및 추가
- 이미지 검증 및 작성 메소드 재사용을 위해 `CurationImageDto` 인터페이스구현 `getContent()`, `getImageIds()` 추가
- `ImageIds` 필드가 존재하지 않으면 유효성 검사에서 에러 나도록 변경
- 이미 큐레이션 작성시 저장한 이미지면 `CurationSaveImage` 테이블을 먼저 삭제 후 이미지 테이블 삭제, S3 스토리지 삭제 순으로 진행
- 본인이 등록한 이미지가 아니면 삭제하거나 등록 할 수 없도록 검증 로직 추가
- 유효성 검사 메세지가 조금 추가 되었고 메소드 재사용을 위해서 postDto, patchDto 모두 매개변수로 넣기 위해 인터페이스를 구현했습니다.
- 한번 보시고 수정해야 하거나 리뷰해주실 부분 있으면 말씀해주세요 !
> feat: 큐레이션 이미지 업로드 유효성 검사 및 수정 기능

- client/src/pages/Curation/CurationDetailPage.tsx
- client/src/pages/Curation/CurationEditPage.tsx
- client/src/pages/Curation/CurationWritePage.tsx
- 큐레이션 공개/비공개 기능 구현
- 자잘한 기능과 버그 수정
- 큐레이션 공개 설정 시, 해당 큐레이션이 모든 사용자에게 보여지도록 구현했습니다.
- 큐레이션 비공개 설정 시, 해당 큐레이션이 작성한 본인에게만 보여지도록 구현했습니다.
- 작성자 본인이 아닌 사용자가 비공개 큐레이션 진입 시, 임시로 alert을 띄웠습니다.
- @Kyunju 님이 구현해 주신 이미지 업로드로 `CurationWritePage`와 `CurationEditPage`에 `imageIds`를 추가했습니다.
- 큐레이션 작성 후 `CurationDetailPage`에 이미지가 container 크기를 벗어나는 경우가 있어, max-width를 제한했습니다.
- `CurationWritePage`와 `CurationEditPage`에서 [취소] 버튼을 누르면 이전 페이지로 이동되도록 구현했습니다.
*좌측은 작성자 본인 | 우측은 작성자 제외한 타유저
https://github.com/codestates-seb/seb44_main_004/assets/123397411/d9244a96-c659-4c3c-8b41-bef268059572
- 피드백은 언제나 환영입니다!
> [Client] 큐레이션 공개/비공개 기능 구현

- server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
- 소셜로그인시 DB에 회원정보없을때 회원가입페이지로 리다이렉트시키는 부분에서 데이터 형식변경
-해당 구글데이터를 queryParm형식으로 추가
> fix: 응답데이터 쿼리파람형식으로 변경

- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 큐레이션을 조회하는 사용자에 따라 해당 큐레이션에 좋아요를 눌렀는지 여부 응답
- `CurationService` 의 `getCuration()` 메소드, `CurationLike` 정보를 가져오는 로직 추가
- `Principal` 을 통해 사용자 조회 및 like 정보 조회
- @Transient 어노테이션으로 `Curation` 엔티티에 정보확인용 필드 생성
- 큐레이션 단일 상세조회를 추후 fetch join을 통해 쿼리문이나 그런 부분을 개선할 필요가 있을 것 같습니다.
- 리뷰 부탁드립니다!
> feat: isLiked 기능 구현

- server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
- server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
- server/src/main/java/com/seb_main_004/whosbook/reply/mapper/ReplyMapper.java
- server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java
- 큐레이션 상세조회에서 댓글리스트를 조회할수있다
- 댓글 조회API추가
- ReplyController,ReplyService,ReplyMapper구현
- 페이지네이션으로구현
- 
> feat:댓글 조회 구현

- server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 좋아요한 큐레이션 목록조회 API가 멤버를 특정하여 기능하도록 수정
--> 로그인한 회원 혹은 지정한 회원이 좋아요한 큐레이션 목록을 조회해야 하는데, 쿼리문 오류로 인해 정상작동하지 않음
- 쿼리문이 지정한 memberId를 인자로 받도록 쿼리문 수정
- 로컬테스트 완료
- 궁금하거나 개선해야할 부분이 있다면 코멘트 남겨주세요.
> fix: 좋아요한 큐레이션 목록조회 API 수정

- server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
- server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
- server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
- server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
- 회원 프로필이미지 CRUD 기능 구현
-> 로그인 후 memberPatch()를 이용하여 프로필 이미지를 추가, 수정 할 수 있음
- 기존에 구현되어 있던, S3StorageService 활용
- 프로필이미지를 기본으로 바꾸거 싶거나, 회원 탈퇴를 하는 경우 S3에 저장된 프로필 이미지 삭제 하도록 구현
- 로컬테스트 완료
-개션할 점이나 궁금한 점이 있다면 코멘트 부탁드립니다!!
> feat: 회원 프로필이미지 CRUD 기능

- server/src/main/java/com/seb_main_004/whosbook/image/utils/ImageStorageUtils.java
- Jpg, JPEG 같이 대문자 확장자 검증이 안되던 문제 해결
- 이미지 확장자 부분을 모두 소문자로 변경
> feat: 이미지 확장자 대소문자 여부 상관없는 검증 기능

- server/src/main/java/com/seb_main_004/whosbook/book/BookService.java
- server/src/main/java/com/seb_main_004/whosbook/book/entity/Book.java
- server/src/main/java/com/seb_main_004/whosbook/book/entity/BookCuration.java
- server/src/main/java/com/seb_main_004/whosbook/book/repository/BookCurationRepository.java
- server/src/main/java/com/seb_main_004/whosbook/book/repository/BookRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 큐레이션 작성시 외부 API와 연동한 책 데이터 저장 기능
- 단일 상세 큐레이션 조회시 큐레이션 작성 때 저장된 책 데이터 조회
- Entity : 
- `Book` - 책정보 테이블
- `BookCuration - `Curation`과 `Book` 다대다 매핑을 위한 연결 테이블
- Repository : `Book`, `BookCration` 저장을 위한 Repository 클래스 작성
- Service : `BookService` - `getSavedBook()` 메소드 구현 :  이미 존재하는 책 데이터인지 확인 -> 존재하면 DB에 있는 Book 데이터 반환 -> 존재하지 않다면 DB에 저장 후 책데이터 반환
- 단일 상세 큐레이션 조회시 책 데이터 조회를 위한 Dto 매핑 작업
- 큐레이션 안에서 책 정보 등록과 조회만 가능하고 책을 별도로 저장하거나 하는 로직은 아직 구현하지 않았습니다.
- 추후 큐레이션 수정시 책정보가 수정 될 때 해당 부분을 반영하는 것도 구현 할 예정입니다.
- 큐레이션 저장시 굉장히 많은 테이블에 저장이 일어나서.. 추후 더 개선 할 수 없는지 고민해봐야 할 것 같습니다
- 생각보다 단일 큐레이션 조회 속도가 빠릅니다? 20ms 미만으로 나오네요 ..
- 참고사항의 예외 처리 이외에 추가로 필요한 부분이 있을 지 조언 부탁드립니다.
> feat: 큐레이션 작성시 책정보 저장 및 조회 기능 구현

- server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
- server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- NEW, BEST 큐레이션 리스트 조회시 카테고리별 필터 기능
- CurationRepository 에서 queryParam 여부에 따라 category가 포함 또는 포함되지 않도록 구현
- new, best GET 매핑된 컨트롤러 메소드에 `category` param 추가
- 일단 지금은 조회시 select 쿼리문이 3번 나가게 됩니다 추후에 한번에 가져 올 수는 없는지 더 공부해보고 리팩토링을 해야 할 수도 있을 것 같습니다.
- QueryDsl의 필요성을 점점 느낍니다.
> feat: 뉴, 베스트 큐레이션 카테고리별 조회 기능

- server/src/main/java/com/seb_main_004/whosbook/advice/GlobalExceptionAdvice.java
- server/src/main/java/com/seb_main_004/whosbook/book/BookService.java
- server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
- server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
- 큐레이션 수정시 책정보 수정 기능
- `CurationService` 에서 `updateCuration()` 메소드 수정
- 책정보가 바뀌었는지 검증하고 큐레이션과 책정보 연결 관계 업데이트 로직 구현
- 공통 advice가 주석처리 되어있어서 다시 주석처리 해제하고 pr 날립니다!
- 일단 단일 책정보에 대한 것만 염두하고 기능을 빠르게 구현했습니다
- 추후 복수 책정보에 대한 부분으로 업데이트 되면 수정하도록 하겠습니다!
> feat: 책정보 수정 기능 구현

- server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/CuratorResponseDto.java
- 단일 큐레이션 조회시 curator 응답값에 프로필이미지 url 추가
- memberToCurator 매핑에 매핑 추가
- CuratorResponseDto에 image 필드 추가
> feat: curator 응답값에 프로필이미지 url 추가

- client/src/components/category/CategoryTag.tsx
- client/src/components/curations/CurationDetailInfo.tsx
- client/src/components/input/SelectBox.tsx
- client/src/pages/Curation/BestCurationPage.tsx
- client/src/pages/Curation/CurationDetailPage.tsx
- client/src/pages/Curation/CurationWritePage.tsx
- client/src/pages/Curation/NewCurationPage.tsx
- client/src/store/categorySlice.ts
- BEST 큐레이션 리스트에서 카테고리 클릭 시 해당 카테고리에 맞는 큐레이션 리스트가 나오도록 구현
- NEW 큐레이션 리스트에서 카테고리 클릭 시 해당 카테고리에 맞는 큐레이션 리스트가 나오도록 구현
- 기존 카테고리 목록을 불러오던 `CategoryTag.tsx`와 `SelecBox.tsx`에서 GET 요청을 통해 모든 카테고리를 불러왔습니다.
- `CurationWritePage.tsx`와 `CurationEditPage.tsx`에 categoryId라는 value값을 추가해, 사용자가 선택한 카테고리가 `CurationDetailPage`에도 나타나도록 구현했습니다.
- API를 사용하여 BEST/NEW큐레이션 페이지에서 특정 카테고리를 선택하면 > 해당 카테고리의 큐레이션이 나오면서 페이지네이션이 가능하도록 구현했습니다.
- 카테고리 조회 요청 시, BEST/NEW큐레이션 페이지에서 특정 카테고리 버튼을 누를 때마다 요청이 전송되기에 조금 비효율적이라는 생각이 들어, @jiye-7 님이 Redux에 저장해주신 데이터를 사용하고자 합니다. 이는 리팩토링 예정입니다.
- 원래 @ella-yschoi 담당하는 파트였으나, @jeongjwon 님이 도와주셔서 함께 작업했습니다.
- BEST 큐레이션 페이지
- NEW 큐레이션 페이지
두 페이지의 첫 렌더링 시 비교를 하면 미교하게 데이터의 순서가 다른 것을 볼 수 있는데,
이는 BEST 큐레이션 페이지에서는 조회 요청을 하면 좋아요 순으로 데이터를 받아오기 때문입니다.
- 피드백은 언제나 환영입니다!
> [Client] Best / New 큐레이션 리스트 + Category API 요청 기능 구현

- client/src/pages/User/MyPage.tsx
- client/src/pages/User/UserPage.tsx
마이페이지, 타유저페이지에서 생긴 이슈를 수정하였습니다.
- 마이페이지에서 구독하는 큐레이터 목록을 보고 있다가 마이페이지 외 다른 페이지를 접속 후, 마이페이지 접속 시 구독하는 큐레이터 목록 에 active 가 된 상태였습니다.
- 이를 필터 값을 초기화 시키는 과정을 진행하였습니다.
- 수정 전
- 수정 후
> 마이페이지, 타유저 페이지에서 목록 오류 수정

- server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
- server/src/main/java/com/seb_main_004/whosbook/member/dto/BestCuratorDto.java
- server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
- server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
- server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
- bestCurator 조회시 N+1 문제 해결을 위한 쿼리 개선
-  각 큐레이터의 구독자 수를 `영속화된 컬렉션.size()` 로 불러서 맵핑하는 부분을 제거
- 데이터 쿼리로 조회된 데이터를 바로 BestCuratorDto에 주입해서 해당 BestCuratorDto를 반환
- 다른 리스트 조회도 조금씩 손봐야 할 것 같습니다.
> refactor: bestCurator 조회시 N+1 문제 해결을 위한 쿼리 개선

- client/src/components/curations/CurationDetailInfo.tsx
- client/src/components/input/SelectBox.tsx
- client/src/components/modals/Modal.tsx
- client/src/pages/Curation/CurationDetailPage.tsx
- client/src/pages/Curation/CurationEditPage.tsx
- client/src/pages/Curation/CurationWritePage.tsx
- client/src/types/index.ts
단일 큐레이션 상세페이지에서의 오류와 편집 페이지에서 카테고리, 책 정보 불러오는 기능을 처리하였습니다.
- 댓글 삭제 아이콘 클릭시 댓글 삭제 확인 모달 창을 띄우고 그 모달의 댓글 삭제 버튼을 눌러야 삭제되는 로직으로 변경하였습니다.
- 삭제시 블랙화면이 꽉차게끔 너비와 높이를 변경하였습니다.
- 편집 페이지에서 카테고리와 책 정리를 불러오는 부분을 수정하면서, 연관된 작성 페이지와 태그 박스 컴포넌트의 코드를 수정하였습니다.
- 뒤로 가기 시 undefined 로 나오는 것은 아직 해결을 못했고 주말에 진행해봐야 할 것 같습니다. (이 부분 도와주시면 감사하겠습니다.)
- 댓글 삭제기능
- 글 작성 후, 편집 완료
> 단일 큐레이션 상세페이지 및 편집 페이지 수정

- server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
인증이만료되었습니다-> 이메일이 존재하지않거나 비밀번호가 불일치합니다 로 에러 메세지 수정
> fix:401에러메시지 수정

- client/src/components/modals/Modal.tsx
- client/src/components/profiles/ProfileInfo.tsx
- client/src/components/profiles/ProfileOut.tsx
- client/src/pages/User/MyPage.tsx
- client/src/types/index.ts
마이페이지에서 생긴 이슈에 대한 리팩토링입니다.
- reset 주석으로 인한 마이페이지 상단 div 에 border 를 제거하였습니다.
- 제거 함에 따라 새롭게 css 를 수정하여 구분선을 만들었습니다.
- 회원 탈퇴시 모달을 띄워 한 번 더 확인 후 탈퇴를 할 수 있도록 하였습니다.
- 그에 따른 Modal 컴포넌트에서 회원 탈퇴의 경우를 추가하였습니다.
- ```Modal``` 컴포넌트에서 ```handleCompleteOut``` 함수 추가
- ```type/index.ts``` 파일에서 ```ModalType``` 에 ```OUT=out``` 추가
- 탈퇴 시 문구는 'BEST 큐레이터가 될 기회를 포기하시겠어요?'로 변경하였습니다.
- 탈퇴 테스트를 진행하였습니다. 로컬에서 데이터가 날라가는 것에 대해 한 건만 테스트를 실행한 것에 있어서 양해부탁드립니다.
- 회원 수정 사항시 모달을 띄우는 것에 대한 의견에 코드를 반영하고자 하였으나, form 태그에 대한 onSubmit 이 연결되어 있어 모달을 띄웠음에도 불구하고 저절로 업데이트 되는 현상으로 모달을 띄우지 않는 것으로 결정하였습니다. 혹여나 시간이 난다면 이 점은 추후에 적용시켜보도록 하겠습니다.
> 마이페지이지 리팩토링 - border 제거, 탈퇴 확인 모달

- client/index.html
- client/src/components/quill/QuillEditor.tsx
- client/src/styles/GlobalStyles.ts
- Quill 기능 추가 및 버그 수정
- Editor에서 작성 후 큐레이션 단일 상세페이지에서 bold, italic, heading 등 **스타일 적용이 되지 않은 버그를 해결**했습니다.
- 드래그해야 이미지를 넣을 수 있었던 점은 **Quill 테마 변경**을 하여 드래그하지 않아도 **이미지 버튼이 보이게끔 수정**했습니다.
- **이미지 붙여넣기 금지 기능**을 추가했고, 붙여넣기 시 customAlert을 띄워 주었습니다.
- **이미지는 2MB 이하로 업로드** 되도록 제한을 걸어두었고, 용량 초과 시 `customAlert`을 띄워 주었습니다.
- 지난 멘토링 때 멘토님이 텍스트까지 붙여넣기 불가할까 우려하셨으나, 다행히 **이미지만 붙여넣기 불가하도록 구현**할 수 있었습니다.
- 코드가 살짝 뒤죽박죽인데, 우선 기능구현 먼저 하고 추후에 리팩토링 진행하겠습니다.
- 아래 영상에서는 이미지 업로드 속도가 살짝 느린데, 현재 제 로컬에서 네트워크 속도 자체가 느린 점 참고해 주세요!
https://github.com/codestates-seb/seb44_main_004/assets/123397411/3aeab0a8-b424-4551-99f0-1aac191b7336
- 피드백은 언제든지 환영입니다.
> [Client] Quill Editor 기능 추가 및 버그 수정

- client/src/components/profiles/CuratorList.tsx
- client/src/components/profiles/LikeList.tsx
- client/src/components/profiles/ProfileInfo.tsx
- client/src/components/profiles/ProfileOut.tsx
- client/src/components/profiles/WrittenList.tsx
- client/src/types/profile.ts
- 작성한 큐레이션, 좋아욯나 큐레이션, 구독한 큐레이터 목록에서 데이터가 없을 때 문구 변경
- 마이페이지가 아닌 BEST 큐레이터나 단일 상세 큐레이션 페이지에서 닉네임을 클릭해서 자기 자신의 페이지에 접속했을 때, 마이페이지가 아닌 유저 페이지로 나오는 이슈 (구독하기 버튼 생성) -> 마이페이지로 다시 이동
> 마이페이지 추가 이슈 리팩토링

- client/src/components/curations/CurationProfileInfo.tsx
- client/src/components/profiles/ProfileInfo.tsx
- 마이페이지에서 프로필과 단일 큐레이션 상세 페이지에서 프로필 이미지를 꽉 차게 height 를 변경하였습니다.
- (정사각형이 아닌 직사각형의 이미지를 업로드 시 )
|변경 전| 변경 후|
|:--:|:--:|
|![image](https://github.com/codestates-seb/seb44_main_004/assets/76391160/7232397b-34aa-4ad2-81bb-212e94de32f9)|![image](https://github.com/codestates-seb/seb44_main_004/assets/76391160/81715b8b-59d6-4a53-a958-5b20f49fa3fd)|
> 프로필 이미지 리팩토링

- client/src/components/input/SelectBox.tsx
- client/src/pages/Curation/CurationEditPage.tsx
- client/src/pages/Curation/CurationWritePage.tsx
기존에 있던 유효성검사를 대체하여 직접 만든 `useInput` 커스텀 Hook을 이용하여 대체하였습니다.
This closes #296
> #296 큐레이션 수정 페이지 유효성 검증 적용

- client/src/components/curations/CurationCreatedDate.tsx
- client/src/components/profiles/ProfileInfo.tsx
- client/src/components/replies/ReplyCreatedDate.tsx
- client/src/components/replies/ReplyProfileInfo.tsx
- client/src/pages/Curation/CurationDetailPage.tsx
- client/src/pages/Curation/CurationEditPage.tsx
- client/src/pages/Curation/CurationWritePage.tsx
- client/src/styles/GlobalStyles.ts
- 전체적으로 다른 페이지들보다 크고 넓은 느낌이었던 큐레이션 단일 상세 조회 페이지를 수정
- Quill Editor 테마 변경으로 작성/수정 페이지의 필요없는 **Label을 삭제**했습니다. (드래그해서 이미지 등록 가능하다는 문구)
- 전체적인 조회 페이지 Container의 **width를 줄였습니다.**
- 댓글과 큐레이션의 **업로드 일자의 텍스트** 및 **수정/삭제 아이콘의 크기**를 기존보다 줄였습니다.
- `ProfileInfo`의 소개글이 없다는 문구를 `~습니다` 체에서 `~요` 체로 통일했습니다.
- `ReplyProfileInfo`의 댓글 **내용 폰트 크기를 축소**했습니다.
- `GlobalStyles`에 컨텐츠, 댓글에 적용할 **SpoqaHanSansNeo-Light**을 추가했습니다.
- 반응형 적용은 아직 작업중입니다.
https://github.com/codestates-seb/seb44_main_004/assets/123397411/74368607-ae29-495d-b0ac-fcd12d06862a
- `CuratioinDetailPage` 스타일 작업이기에 지원님이 작업하신 부분의 스타일을 몇 가지 수정했는데, 의견 있으시면 말씀 부탁드립니다!
- 더불어, 여러분의 맥북에서도 너무 작아보이거나 여전히 커보이지 않는지 확인 부탁드립니다.
> [Client] 큐레이션 단일 상세 조회 페이지 스타일 수정

- client/src/components/cards/CurationCard.tsx
- client/src/components/cards/MainCurationCard.tsx
- client/src/utils/removeImgTags.ts
react-quill editor의 HTML 문자열에서
- 이미지 태그의 src, alt 속성 제거
- 모든 태그에서 스타일 속성 제거
- <h1> ~ <h6> 모든 heading 태그를 <p> 태그로 대체
- <u> 태그 제거
- text-decoration: underline 스타일 제거
- text-decoration: line-through 스타일 제거
> fix: react-quill HTML태그들에서 모든 스타일 제거

- client/src/api/axios.ts
- client/src/api/userApi.ts
- client/src/components/alert/sweetAlert.ts
- client/src/components/curations/CurationDetailInfo.tsx
- client/src/components/curations/CurationProfileInfo.tsx
- client/src/components/profiles/ProfileInfo.tsx
- client/src/pages/Curation/BestCurationPage.tsx
- client/src/pages/Curation/NewCurationPage.tsx
- client/src/pages/User/SignIn.tsx
**버그 수정사항**
- 탈퇴한 계정으로 로그인하려고 할 때 Alert 처리, 회원가입 페이지로 갈것인지 체크
- 상세 페이지에서 로그인 하지 않았을 때 좋아요 누르면 Aelrt 처리, 로그인 페이지로 갈것인지 체크
- 상세 페이지에서  로그인 하지 않았을 때 구독하기 누르면 Aelrt 처리, 로그인 페이지로 갈것인지 체크
> fix: 회원탈퇴 시 알림 문구 변경, Sweet Alert 처리안된 부분 추가

- server/build.gradle
- server/src/main/java/com/seb_main_004/whosbook/advice/ErrorSlackConnectTestController.java
- server/src/main/java/com/seb_main_004/whosbook/advice/GlobalExceptionAdvice.java
- server/src/main/resources/application.yml
- Exception 처리를 하지 않은 모든 Exception을 슬랙 알림으로 받을 수 있도록 연동
- `build.gradle` 에 slack-api-client 의존성 추가 : 취약점 이슈가 없고 최근까지 업데이트가 일어남
- `GlobalExceptionAdvice` 에서 최종적으로 `Exception`을 잡는 부분에 Slack 전송 기능 추가
- 에러 테스트를 위한 요청시 무조건 에러를 던지는 컨트롤러 추가
- 추후에는 `logback` 을 사용한 로그 적재, 분류등을 통해서 더욱 다양하게 구현 할 수 있을 것 같습니다.
> feat: Unhandled Exception 슬랙 연동
